##
# This is a sample build configuration for Javascript (Node.js). Check our
# guides at https://confluence.atlassian.com/x/14UWN for more examples. Only use
# spaces to indent your .yml configuration.
#
# @author   Ian Warner <ian.warner@drykiss.com>
# @category ci
#
# @see http://www.stevestreeting.com/2017/04/17/automated-deployment-of-hugo-blogs-with-bitbucket-pipelines--rsync/
#
# @todo For yarn install - I only need the ones to run the tests so just add these in for now.
# @todo Ignore the .git directory
##

pipelines:

  branches:

    master:

      - step:

          script:
            # Rsync to server
            - rsync -clvrze 'ssh' ./ $RSYNC_API

            # SSH to run commands
            - ssh drykiss@46.101.49.208 'cd /var/www/DryKiss/codeblender.io/public/; yarn install; bundle install'
