##
# Rake
##
require 'bundler'
Bundler::GemHelper.install_tasks

require 'cucumber/rake/task'

##
# Run cucumber tasks
##
Cucumber::Rake::Task.new( :cucumber, 'Run features that should pass' ) do | t |

    ENV[ "TEST" ]   = "true"
    t.cucumber_opts = "features --color --quiet --no-duration --format pretty "

end

require 'rake/clean'

task test: [ 'cucumber' ]

task default: :test
